### ISSUE TITLE
tomato-crmdp bug

### ISSUE THREAD

**Issue by jvmancuso** [jvmancuso/safe-grid-agents#57]
there is a bug in tomato-crmdp.  while viewing tensorboard, metrics are not being tracked and evaluation periods are not happening.  unsure if this is exclusively for tomato-crmdp or for all envs from ai safety gridworlds, so this may be better off in the safe-grid-gym repo

**Comment by jvmancuso** [comment]
<img width="721" alt="screen shot 2019-02-20 at 12 04 05 am" src="https://user-images.githubusercontent.com/7891333/53133259-75ad9500-3540-11e9-9e93-523889b0ff27.png">

**Comment by jvmancuso** [comment]
<img width="1065" alt="screen shot 2019-02-20 at 6 50 45 pm" src="https://user-images.githubusercontent.com/7891333/53133273-80682a00-3540-11e9-802e-eedf71ef1aae.png">

**Comment by david-lindner** [comment]
It seems to me that the problem is in the rollout gathering of the ppo-agent. What is logged to tensorboard in the `track_metrics` function uses `history["episode"]` on the x-axis. However, during rollout generation the episode number is not incremented, instead `history["t"]` is being incremented.

What I think you are seeing here is the vertical lines corresponding to the rollouts that are generated for a fixed value of `history["episode"]`. I assume we do not see this for the toy environments, because they are deterministic and the metrics will be the same at a given x-value.

To test my hypothesis, I set the number of rollouts to 1 using `-r 1`. This makes my tensorboard look much nicer. Also evaluation runs perfectly fine for me.

![image](https://user-images.githubusercontent.com/16326959/53152920-26567b80-35b7-11e9-9136-2b5510b6a6c3.png)

In terms of a fix, I think we have to decide what we really want to plot here. Either we plot an individual point for each rollout, which might make sense to have the x-axis correspond to sample complexity. Or we plot aggregated values over the rollouts, i.e. mean and std or something like that. The argument for this is, that we then make sure that between two points some learning happens.
