### ISSUE TITLE
Wrong assumptions about board_shape in toy envs

### ISSUE THREAD

**Issue by timorl** [jvmancuso/safe-grid-agents#66]
@alok brought this up in slack, in some places in the code we assume that `board_shape` has length 3, while for the toy envs it has length 2. There are three offending lines, just grep `board_shape[2]`.

**Comment by david-lindner** [comment]
The problem seemed to be caused by a change in the shape of the observations when adding the option to have transitions in the obervations of the `ai-safety-gridworlds`. This was adapted accordingly in the observations the toy environments return, but not in the observation space which is used in `safe-grid-agents` to determine the shape of observations initially. For the fix, see https://github.com/david-lindner/safe-grid-gym/pull/28
